name: crm-frontend-deploy

on:
  push:
    branches: ["main"]  # Deploy when pushing to main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Check if VITE_API_URL secret is available
        run: |
          if [ -z "${{ secrets.VITE_API_URL}}" ]; then
            echo "VITE_API_URL is not set. Cancelling the workflow."
            exit 1
          fi

      - name: Create .env file
        run: |
          cd frontend
          echo "VITE_API_URL=${{ secrets.VITE_API_URL}}" > .env

      - name: Build the Vite app
        run: |
          cd frontend
          npm run build

      - name: Create 404.html for SPA routing
        run: |
          cd frontend
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
